### ISSUE TITLE
Update strategy of dots and lines

### ISSUE THREAD

**Issue by thetwom** [halilozercan/madewithcompose#4]
Hi, I stumbled over your "DotsAndLines"-implementation and I am wondering about your opinion of having copies of the DotsAndLinesState at each update step. To me it seems like the underlying dot-list is copied quite often and I wonder, if such a strategy is can be viewed as good practice and without real performance issues for compose apps.

**Comment by halilozercan** [comment]
Yes, that logic is not optimized at all and I wouldn't recommend anyone use that kind of approach in production. This repository has always been about experimental stuff that I wanted to try with Compose.

**Comment by thetwom** [comment]
Thanks for your opinion.
